[build-system]
build-backend = "pdm.backend"
requires = ["pdm-backend"]

[project]
authors = [
    {email = "louismmx@gmail.com", name = "Louis Maddox"},
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: Pydantic :: 2",
    "Framework :: Pydantic",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries",
]
dependencies = [
    "msgspec>=0.18.5",
    "defopt>=6.4.0",
]
description = "Git diff handling in Python."
dynamic = ["version"]
keywords = [
    "git",
    "pydantic",
    "pypi",
]
license = {text = "MIT"}
name = "emptypt"
readme = "README.md"
requires-python = ">=3.11,<3.12"

[project.scripts]
emptypt-minimum = "emptypt.core.minimal_op:bar"
emptypt-simple = "emptypt.core.action:foo"
emptypt-defopt = "emptypt.cli.msgspec_cli:run_cli"

[project.urls]
Homepage = "https://github.com/lmmx/emptypt"
Repository = "https://github.com/lmmx/emptypt.git"

[tool.isort]
known_first_party = ["emptypt"]

[tool.pdm]
version = {path = "src/emptypt/__init__.py", source = "file"}

[tool.pdm.dev-dependencies]
develop = [
    "pysnooper>=1.2.0",
]
docs = [
    "mkdocs-material[recommended,imaging]>=9.5.2",
    "mkdocs>=1.5.3",
    "mkdocstrings>=0.24.0",
]
mkdocs = []
test = [
    "pytest>=7.4.0",
]

[tool.ruff]
ignore = ["C408", "C901", "E501", "E741"]
ignore-init-module-imports = true
select = ["C", "E", "F", "I", "W"]

[tool.ruff.isort]
lines-after-imports = 2

[tool.ruff.lint.isort]
known-first-party = ["emptypt"]

[tool.ruff.per-file-ignores]
# Ignore `E401` (unused imports) in all `__init__.py` files.
"__init__.py" = ["E401"]

[tool.tomlsort]
all = true
in_place = true
spaces_before_inline_comment = 2  # Match Python PEP 8
spaces_indent_inline_array = 4  # Match Python PEP 8
trailing_comma_inline_array = true
