[project]
dependencies = []
description = "Add your description here"
name = "simple-cli"
readme = "README.md"
requires-python = ">=3.11, <3.12"
version = "0.1.0"

[project.scripts]
entrypt-minimum = "simple_cli.minimal_op:bar"
entrypt-simple = "simple_cli.action:foo"
