[project]
dependencies = [
    "click>=8.1.7",
    "msgspec>=0.18.5",
]
description = "Add your description here"
name = "click-cli"
readme = "README.md"
requires-python = ">=3.11, <3.12"
version = "0.1.0"

[project.scripts]
emptypt-click = "click_cli.main:run_cli"
