[project]
dependencies = [
    "argh>=0.30.4",
    "pydantic>=2.9.0",
]
description = "Add your description here"
name = "argh-cli"
readme = "README.md"
requires-python = ">=3.10, <3.12"
version = "0.1.0"

[project.scripts]
emptypt-p-argh = "argh_pyd_cli.main:run_pyd_cli"

[tool.lint.isort]
known_first_party = ["argh_pyd_cli"]

[tool.ruff.lint.isort]
known-first-party = ["argh_pyd_cli"]
