[project]
dependencies = [
    "defopt>=6.4.0",
    "pydantic>=2.9.0",
]
description = "Add your description here"
name = "defopt-cli"
readme = "README.md"
requires-python = ">=3.10, <3.12"
version = "0.1.0"

[project.scripts]
emptypt-p-defopt = "defopt_pyd_cli.main:run_pyd_cli"

[tool.lint.isort]
known_first_party = ["defopt_pyd_cli"]

[tool.ruff.lint.isort]
known-first-party = ["defopt_pyd_cli"]
