[project]
dependencies = [
    "click>=8.1.7",
    "msgspec>=0.18.5",
]
description = "Add your description here"
name = "click-msg-cli"
readme = "README.md"
requires-python = ">=3.10, <3.12"
version = "0.1.0"

[project.scripts]
emptypt-m-click = "click_msg_cli.main:run_cli"

[tool.lint.isort]
known_first_party = ["click_msg_cli"]

[tool.ruff.lint.isort]
known-first-party = ["click_msg_cli"]
