[project]
name = "argh-ds-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.12"
dependencies = []

[project.scripts]
emptypt-argh-docstr = "argh_ds_cli.main:run_cli"
