[project]
dependencies = []
description = "Add your description here"
name = "argh-ds-cli"
readme = "README.md"
requires-python = ">=3.11, <3.12"
version = "0.1.0"

[project.scripts]
emptypt-argh-docstr = "argh_ds_cli.main:run_cli"
