[project]
dependencies = [
    "pydantic>=2.9.0",
]
description = "Add your description here"
name = "simple-pyd-cli"
readme = "README.md"
requires-python = ">=3.10, <3.12"
version = "0.1.0"

[project.scripts]
emptypt-p-minimum = "simple_pyd_cli.minimal_op:bar"
emptypt-p-simple = "simple_pyd_cli.action:foo"

[tool.lint.isort]
known_first_party = ["simple_pyd_cli"]

[tool.ruff.lint.isort]
known-first-party = ["simple_pyd_cli"]
