[project]
dependencies = [
    "pydantic>=2.9.0",
]
description = "Add your description here"
name = "argh-ds-pyd-cli"
readme = "README.md"
requires-python = ">=3.10, <3.12"
version = "0.1.0"

[project.scripts]
emptypt-p-argh-docstr = "argh_ds_pyd_cli.main:run_cli"

[tool.lint.isort]
known_first_party = ["argh_ds_pyd_cli"]

[tool.ruff.lint.isort]
known-first-party = ["argh_ds_pyd_cli"]
