[project]
dependencies = ["argh>=0.30.4"]
description = "Add your description here"
name = "argh-cli"
readme = "README.md"
requires-python = ">=3.11, <3.12"
version = "0.1.0"

[project.scripts]
emptypt-argh = "argh_cli.main:run_cli"
