[project]
dependencies = []
description = "Add your description here"
name = "emptypt"
readme = "README.md"
requires-python = ">=3.10, <3.12"
version = "0.1.0"

[tool.lint.isort]
known_first_party = ["emptypt"]

[tool.ruff.lint.isort]
known-first-party = ["emptypt"]

