[project]
dependencies = [
    "pydantic>=2.9.0",
    "typer>=0.9.0",
]
description = "Add your description here"
name = "typer-cli"
readme = "README.md"
requires-python = ">=3.10, <3.12"
version = "0.1.0"

[project.scripts]
emptypt-p-typer = "typer_pyd_cli.main:run_pyd_cli"

[tool.lint.isort]
known_first_party = ["typer_pyd_cli"]

[tool.ruff.lint.isort]
known-first-party = ["typer_pyd_cli"]
