[project]
dependencies = [
    "click>=8.1.7",
    "pydantic>=2.9.0",
]
description = "Add your description here"
name = "click-pyd-cli"
readme = "README.md"
requires-python = ">=3.10, <3.12"
version = "0.1.0"

[project.scripts]
emptypt-p-click = "click_pyd_cli.main:run_cli"

[tool.lint.isort]
known_first_party = ["click_pyd_cli"]

[tool.ruff.lint.isort]
known-first-party = ["click_pyd_cli"]
